#!/bin/bash
#
# Tunnel	create/delete POINTOPOINT tunnel
#
# chkconfig: 2345 10 90
# description: ptp tunnel or gre tunnel
# Author: Xu Panda
# Last update: 2015-01-24

# Warning: 
# This script will exchage ser's router,
# when it restart you should check it best,and add monitor!

# Define all ip infomation like:
# *******************************************
# * info="name lo_pub re_pub lo_pri re_pri" *
# *******************************************
# name: tunnel name;
# lo_pub: local real ip address;
# re_pub: remote real ip address;
# lo_pri: local private ip address,if ptp no netmask,if gre netmask should be /30;
# re_pri: remote private ip address;

DIR=$(cd `dirname $0`;echo $PWD)
# start as system turn on
st () {
	local sc=/etc/init.d/tunnel
	if [ ! -L $sc ];then
		file=$(echo $0 | awk -F'/' '{print $NF}')
		me=$DIR/$file
		/bin/ln -s $me $sc
	fi
}

# create tunnel
cre_ptp () {
	/sbin/modprobe ipip 
	/sbin/ip tunnel add $name mode ipip remote $re_pub local $lo_pub
	/sbin/ip link set $name up
	/sbin/ifconfig $name $lo_pri pointopoint $re_pri
}

cre_gre () {
	/sbin/modprobe ip_gre
	/sbin/ip tunnel add $name mode gre remote $re_pub local $lo_pub ttl 64
	/sbin/ip addr add $lo_pri dev $name
	/sbin/ip link set $name up
}

del_tun () {
	/sbin/ip addr | grep -iw POINTOPOINT | \
		awk '{print $2}' | \
		awk -F':' '{print $1}' | \
		awk -F'@' '{print $1}' | \
	while read tun;do
		/sbin/ip tun del $tun
	done
}

# renew router
ren_rou () {
	/sbin/ip route | grep -q -w "192.168.0.0/16"
	if [ $? -eq 0 ];then
		ip route del 192.168.0.0/16
	fi
	ip route add 192.168.0.0/16 dev "$name"
	#/sbin/ip route | grep -q -w "10.9.0.0/16"
	#if [ $? -ne 0 ];then
	#	ip route add 10.9.0.0/16 dev "$name"
	#fi
	/sbin/ip route | grep -q -w "172.16.0.0/12"
	if [ $? -eq 0 ];then
		ip route del 172.16.0.0/12
	fi
	ip route add 172.16.0.0/12 dev "$name"

	#ip r del default
        #ip r add default dev "$name"
}

# ip_forword
ip_forword () {
	forword=$(cat /proc/sys/net/ipv4/ip_forward)
	if [ $forword -ne 1 ];then
		/sbin/sysctl -w net.ipv4.ip_forward=1 > /dev/null
	fi
}

# nat
nat () {
	# Define your public eth.
	ifconfig | grep "inet addr" | \
		egrep -v '172\.1[6-9]\.' | egrep -v ':172\.2[0-9]\.' | egrep -v ':172\.3[0-1]\.' | \
		egrep -v ':10.' | egrep -v ':192.168.' | egrep -v ':127.0.0.1' | \
		sed -n '1p' \
		&> /tmp/pub.ip
	if [ $? -eq 0 ];then
		pub_ip=$(cat /tmp/pub.ip | awk '{print $2}' | awk -F':' '{print $2}')
		pub_eth=$(ifconfig | grep -B1 -w $pub_ip | sed -n '1p' | awk '{print $1}')
		cat /etc/sysconfig/iptables | grep -iw MASQUERADE | grep -q '172.16.0.0/12'
		if [ $? -ne 0 ];then
			iptables -t nat -A POSTROUTING -s 172.16.0.0/12 -o $pub_eth -j MASQUERADE
		fi
		/etc/init.d/iptables save > /dev/null
		/etc/init.d/iptables start > /dev/null
	fi
}

chk_tun () {
	ifconfig | grep -q -w $name
	if [ $? -eq 0 ];then
		echo -e "\n\e[31m$name already exits.no create.\e[0m\n"
		continue
	fi
}
dir=/ROOT/sh/tunnel
doptp () {
	cat $dir/tuninfo | while read name lo_pub re_pub lo_pri re_pri;do
		chk_tun
		cre_ptp
	done
}

dogre () {
	cat $dir/greinfo | while read name lo_pub re_pub lo_pri re_pri;do
		chk_tun
		cre_gre
	done
}

cre () {
doptp

###############################################################################################
##. if aly ser then turn on nat.

#nat
###############################################################################################

##.
ip_forword
# As new eth,so should reload snmpd v3.
/etc/init.d/snmpd restart &> /dev/null
}

rou_254 () {
	name=gw01
	ren_rou
}

rou_253 () {
	name=gw02
	ren_rou
}

case $1 in
	start)
		echo -n "Creating tunnels: ..."
		cre
		rou_254
		st && /sbin/chkconfig tunnel on
		sleep 1 && echo -e "					[\e[32mOK\e[0m]"
		;;
	stop)
		echo -n "Deleting tunnels: ..."
		del_tun
		/sbin/chkconfig tunnel off && rm -rf /etc/init.d/tunnel
		sleep 1 && echo -e "					[\e[32mOK\e[0m]"
		;;
	rerou)
		desrou=$2
                if [ -z $desrou ] || [ $desrou != 253 -a $desrou != 254 ];then
                        echo "Useage: $0 rerou {253|254}"
                        exit 2
                fi
                if [ $2 == 253 ];then
                        rou_253
                fi
                if [ $2 == 254 ];then
                        rou_254
                fi
                ;;
	*)
		echo -e "Useage:$0 {start|stop|rerou} \n
		\e[32mstart\e[0m = \e[32mcreate\e[0m tunnel \n
		\e[31mstop\e[0m = \e[31mdelete\e[0m tunnel\n
		rerou = change pri default gw\n"
esac
